apiVersion: apps/v1
kind: Deployment
metadata:
  name: entidades-solinfbroker
  labels:
    app: entidades-solinfbroker
spec:
  replicas: 4
  selector:
    matchLabels:
      app: entidades-solinfbroker
  template:
    metadata:
      labels:
        app: entidades-solinfbroker
    spec:
      containers:
      - name: entidades-solinfbroker
        image: jvlr9510/jvlr9510-api-entities:1.0
        ports:
        - containerPort: 8082

