apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-pv
  namespace: solinfbroker
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ./postgres-dada

