spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: autenticacao
        uri: lb://autenticacao
        predicates:
        - Path=/auth/**
        filters:
        - AuthenticationFilter
      - id: entidades
        uri: lb://entidades
        predicates:
        - Path=/produtos/**
        filters:
        - AuthenticationFilter
            
            

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://172.20.0.3:8761/eureka
