apiVersion: apps/v1

kind: Deployment

metadata:
  name: database-solinfbroker-deployment
  namespace: solinfbroker
  labels:
    app: database-solinfbroker

spec:
  replicas: 1
  selector:
    matchLabels:
      name: database-solinfbroker-deployment
      app: database-solinfbroker
  template:
    metadata:
      name: database-solinfbroker-deployment
      labels:
        name: database-solinfbroker-deployment
        app: database-solinfbroker
    spec:
      containers:
      - name: database-solinfbroker-deployment
        image: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: "root"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data-volume
          mountPath: /var/lib/postgresql/data
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: postgres-data-volume
        persistentVolumeClaim:
          claimName: postgres-data-pvc
      - name: initdb
        configMap:
          name: postgres-init-script

