version: '3.1'
services: 
    registro-solinfbroker:
        build: ./registro/
        ports:
            - "8761:8761"
        networks:
            solinfbroker-network:
                ipv4_address: "172.20.0.3"

networks:
    solinfbroker-network:
        external: true
        