name: Start Servidor

on:
  push:
    branches: [ "michael" ]

jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3

    # Instalar Docker
    - name: Instalar o Docker
      run: |
        if ! command -v docker &> /dev/null; then 
          echo "Docker não encontrado."
        else
          echo "Docker já instalado."
        fi
      
    # # Logar na conta do DockerHub
    # - name: Logar no DockerHub
    #   run: docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}} docker.io


    # # Adicionar tag na imagem do Registro Serviçe
    # - name: Adicionar tag na imagem do Registro Service
    #   run: docker tag teste-microservice_registro-solinfbroker:0.0.1 solinfbroker/teste-microservice_registro-solinfbroker:latest
    
    # # Subir imagem do registro para o dockerhub 
    # - name: Subir imagem do registro para o dockerhub
    #   run: docker push solinfbroker/teste-microservice_registro-solinfbroker:0.0.1

    # - name: print container
    #   run: docker image ls
  