name: Teste versionamento docker hub

on:
  push:
    branches: [ "rafael" ]

jobs:
  build: 
    runs-on: ubuntu-latest    
    
    steps:
    - uses: actions/checkout@v3

    # Criar imagem da aplicação Registro de Serviço
    - name: Extract metadata (tags, labels)
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: my-docker-hub-namespace/my-docker-hub-repository
      
    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    
    # visualizar imagem
    - name: visualizar imagem
      run: docker image ls
      
    # Logar na conta do DockerHub
    - name: Logar no DockerHub
      run: docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}} docker.io
    
    # Subir imagem do registro para o dockerhub 
    - name: Subir imagem do registro para o dockerhub
      run: docker push solinfbroker/registro-solinfbroker --all-tags

    - name: print container
      run: docker image ls
